package com.evertecinc.b2c.enex.client.model.dto2;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import com.evertecinc.b2c.enex.client.model.dto.AreaDTO;
import com.evertecinc.b2c.enex.client.model.dto.CityDTO;
import com.evertecinc.b2c.enex.client.model.dto.RegionDTO;

import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
public class RegisterClientDTO {

	private Long idClient;
	private String name;
	private String upi;
	private String legalName;
	private String commercialType;
	private String contactName;
	private String contactPhone;
	private String contactEmail;
	private String accountJdeClient;
	private String accountJdeInvoice;
	private String accountJdeTicket;
	private String clientStatus;
	private String clientType;
	private LocalDateTime dateins;
	private LocalDateTime dateupd;
	private String addressStreetName;
	private String addressStreetNumber;
	private String addressDoorNumber;
	private String addressDisStreetName;
	private String addressDisStreetNumber;
	private String addressDisDoorNumber;
	private Long addressIdArea;
	private Long addressDisIdArea;
	private Long addressDisIdRegion;
	private Long addressIdRegion1;
	private Long addressDisIdCity;
	private Long addressIdCity1;
	private String codeOrpakClient;
	private String codeOrpakInvoice;
	private String codeOrpakTicket;
	private AreaDTO areaDTO;
	private CityDTO cityDTO;
	private RegionDTO regionDTO;
	private AreaDTO areaFDTO;
	private CityDTO cityFDTO;
	private RegionDTO regionFDTO;
	private EjecutivoDTO ejecutivoDTO;
	private JefeZonaDTO jefeZonaDTO;
	private BigDecimal creditLimit;
	private BigDecimal remainingAmount;
	private String locked;
	private String isCredit;
	private String warningStockChannel;
	private BigDecimal warningStock;
	private String warningStockCelular;
	private String warningStockEmail;
	private String warningLockedChannel;
	private String warningLockedEmail;
	private Long idJfefeZona;
	private Long idEjecutivo;
	private Boolean factDepartment;
	private LocalDateTime factDepartmentDate;
	private Boolean controlPass;
	private String storelistorpak;
	private Boolean adblue;
	private Boolean vGps;
	private Boolean gpsBasic;
	private Boolean antifraude;
	private Boolean cambus;
	private Boolean telemedicion;
	private String gps;
	private String tipoReglamento;
	private String customerContractCd;
	private String legalNamePerson;
	private String legal_upi;
	private String legalCivilStatus;
	private String legalProfession;
	private String domicilioRLegal;
	private String telefonoRLegal;
	private String mailRLegal;
	private String nombreRLegal2;
	private String rutRLegal2;
	private String estadoCivilRLegal2;
	private String profesionRLegal2;
	private String domicilioRLegal2;
	private String telefonoRLegal2;
	private String mailRLegal2;
	private String calle1;
	private String numero1;
	private String deptoCasa1;
	private String comuna1;
	private String ciudad1;
	private String region1;
	private String calle2;
	private String deptoCasa2;
	private String numero2;
	private String comuna2;
	private String ciudad2;
	private String region2;
	private boolean putSaf = false;
//	private String nombreContacto;
//	private String apellidoContacto;
//	private String cargoContacto;
//	private String mailContacto;
//	private String telContacto;

}